on:
  push:
    tags:
      - "*"

name: Release

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix shell # Test the waters
        run: nix develop -L --verbose

      - name: build odiff
        run: |
          nix develop -c bash -c '
            set -e
            cd odiff
            zig build
          '

      - name: build jniLibs
        run: |
          mkdir -p ./android-diff/src/main/jniLibs
          cp -rvf ./odiff/zig-out/* ./android-diff/src/main/jniLibs

      - name: upload library
        uses: softprops/action-gh-release@v1
